#
# Copyright 2005  Hon Hai Precision Ind. Co. Ltd.
#  All Rights Reserved.
# No porti

#For Compiler Option, add by Jasmine Yang, 03/27/2006
CONFIG_PPTP=n
#CONFIG_BPA=y
CONFIG_RIP=n
CONFIG_NEW_WANDETECT=y
#Foxconn added by Max Ding, 11/25/2008 for multi_language, use pppoe2
CONFIG_SINGLE_PROCESS_PPPOE=n
MPOE_ENABLE_FLAG=n
CONFIG_STATIC_PPPOE=n

ifeq ($(PROFILE),R8000)
SAMBA_ENABLE_FLAG=y
CONFIG_NTFS_3G=n
#CONFIG_MTOOLS=y /* Foxconn, makred by MJ., for 3400v2 downsizing., 2011.02.21.  */
FTP_ACCESS_USB_FLAG=y
CONFIG_DLNA=y
CONFIG_L2TP=y
CONFIG_IGMP_PROXY=y
CONFIG_ISERVER=y
CONFIG_TIMEMACHINE=y
CONFIG_KERNEL_2_6_36=y
CONFIG_OPENVPN=y
CONFIG_TCPDUMP=y
CONFIG_DOWNLOADER=n
endif

ifeq ($(PROFILE),R7800)
SAMBA_ENABLE_FLAG=y
CONFIG_NTFS_3G=n
#CONFIG_MTOOLS=y /* Foxconn, makred by MJ., for 3400v2 downsizing., 2011.02.21.  */
FTP_ACCESS_USB_FLAG=y
CONFIG_DLNA=y
CONFIG_L2TP=y
CONFIG_IGMP_PROXY=y
CONFIG_ISERVER=y
CONFIG_TIMEMACHINE=y
CONFIG_KERNEL_2_6_36=y
CONFIG_OPENVPN=y
CONFIG_TCPDUMP=y
CONFIG_DOWNLOADER=n
#Foxconn add start, Snoopy.wu, support KWILT, 05/20/2015
CONFIG_KWILT=n
#foxconn Han added, 09/03/2015
CONFIG_LINK_AGG=y
CONFIG_PORTTRUNKING_SUPPORT=y
CONFIG_BT_IGMP=y
endif

ifeq ($(PROFILE),R8000P)
SAMBA_ENABLE_FLAG=y
CONFIG_NTFS_3G=n
#CONFIG_MTOOLS=y /* Foxconn, makred by MJ., for 3400v2 downsizing., 2011.02.21.  */
FTP_ACCESS_USB_FLAG=y
CONFIG_DLNA=n
CONFIG_L2TP=y
#CONFIG_IGMP_PROXY=y
CONFIG_ISERVER=n
CONFIG_TIMEMACHINE=y
CONFIG_KERNEL_2_6_36=y
CONFIG_OPENVPN=y
CONFIG_TCPDUMP=y
CONFIG_DOWNLOADER=n
#Foxconn add start, Snoopy.wu, support KWILT, 05/20/2015
CONFIG_KWILT=n
#foxconn Han added, 09/03/2015
CONFIG_LINK_AGG=y
CONFIG_PORTTRUNKING_SUPPORT=y
#CONFIG_BT_IGMP=y
CONFIG_ARNONAT=y
CONFIG_ORANGE_ISP=n
CONFIG_PCRE=y
CONFIG_LIGHTTPD=y
endif

ifeq ($(PROFILE),AX6000)
SAMBA_ENABLE_FLAG=y
CONFIG_NTFS_3G=n
#CONFIG_MTOOLS=y /* Foxconn, makred by MJ., for 3400v2 downsizing., 2011.02.21.  */
FTP_ACCESS_USB_FLAG=y
CONFIG_DLNA=y
CONFIG_L2TP=y
#CONFIG_IGMP_PROXY=y
CONFIG_ISERVER=n
CONFIG_TIMEMACHINE=y
CONFIG_KERNEL_2_6_36=y
CONFIG_OPENVPN=y
CONFIG_TCPDUMP=y
CONFIG_DOWNLOADER=n
#Foxconn add start, Snoopy.wu, support KWILT, 05/20/2015
CONFIG_KWILT=n
#foxconn Han added, 09/03/2015
CONFIG_LINK_AGG=y
CONFIG_PORTTRUNKING_SUPPORT=y
#CONFIG_BT_IGMP=y
CONFIG_ARNONAT=y
CONFIG_ORANGE_ISP=n
CONFIG_PCRE=y
CONFIG_LIGHTTPD=y
endif
ifeq ($(PROFILE),AX11000)
SAMBA_ENABLE_FLAG=y
CONFIG_NTFS_3G=n
#CONFIG_MTOOLS=y /* Foxconn, makred by MJ., for 3400v2 downsizing., 2011.02.21.  */
FTP_ACCESS_USB_FLAG=y
CONFIG_DLNA=y
CONFIG_L2TP=y
#CONFIG_IGMP_PROXY=y
CONFIG_ISERVER=n
CONFIG_TIMEMACHINE=y
CONFIG_KERNEL_2_6_36=y
CONFIG_OPENVPN=y
CONFIG_TCPDUMP=y
CONFIG_DOWNLOADER=n
#Foxconn add start, Snoopy.wu, support KWILT, 05/20/2015
CONFIG_KWILT=n
#foxconn Han added, 09/03/2015
CONFIG_LINK_AGG=y
CONFIG_PORTTRUNKING_SUPPORT=y
#CONFIG_BT_IGMP=y
CONFIG_ARNONAT=y
CONFIG_ORANGE_ISP=n
CONFIG_PCRE=y
CONFIG_LIGHTTPD=y
endif

ifeq ($(PROFILE),RAX20)
IPV6RD_ENABLE_FLAG=y
INCLUDE_IPV6_FLAG=y
CONFIG_PPTP=y
CONFIG_RIP=y
CONFIG_SINGLE_PROCESS_PPPOE=y
MPOE_ENABLE_FLAG=y
CONFIG_STATIC_PPPOE=y
SAMBA_ENABLE_FLAG=y
CONFIG_NTFS_3G=n
#CONFIG_MTOOLS=y /* Foxconn, makred by MJ., for 3400v2 downsizing., 2011.02.21.  */
FTP_ACCESS_USB_FLAG=y
CONFIG_DLNA=y
CONFIG_L2TP=y
#CONFIG_IGMP_PROXY=y
CONFIG_ISERVER=n
CONFIG_TIMEMACHINE=n
CONFIG_KERNEL_2_6_36=n
CONFIG_OPENVPN=n
CONFIG_TCPDUMP=n
CONFIG_DOWNLOADER=n
#Foxconn add start, Snoopy.wu, support KWILT, 05/20/2015
CONFIG_KWILT=n
#foxconn Han added, 09/03/2015
CONFIG_LINK_AGG=n
CONFIG_PORTTRUNKING_SUPPORT=n
#CONFIG_BT_IGMP=y
CONFIG_ARNONAT=y
CONFIG_ORANGE_ISP=n
CONFIG_PCRE=n
CONFIG_LIGHTTPD=n
endif

ifeq ($(PROFILE),RAX50)
IPV6RD_ENABLE_FLAG=y
INCLUDE_IPV6_FLAG=y
CONFIG_PPTP=y
CONFIG_RIP=y
CONFIG_SINGLE_PROCESS_PPPOE=y
MPOE_ENABLE_FLAG=y
CONFIG_STATIC_PPPOE=y
SAMBA_ENABLE_FLAG=y
CONFIG_NTFS_3G=n
#CONFIG_MTOOLS=y /* Foxconn, makred by MJ., for 3400v2 downsizing., 2011.02.21.  */
FTP_ACCESS_USB_FLAG=y
CONFIG_DLNA=y
CONFIG_L2TP=y
#CONFIG_IGMP_PROXY=y
CONFIG_ISERVER=n
CONFIG_TIMEMACHINE=n
CONFIG_KERNEL_2_6_36=n
CONFIG_OPENVPN=n
CONFIG_TCPDUMP=n
CONFIG_DOWNLOADER=n
#Foxconn add start, Snoopy.wu, support KWILT, 05/20/2015
CONFIG_KWILT=n
#foxconn Han added, 09/03/2015
CONFIG_LINK_AGG=n
CONFIG_PORTTRUNKING_SUPPORT=n
#CONFIG_BT_IGMP=y
CONFIG_ARNONAT=y
CONFIG_ORANGE_ISP=n
CONFIG_PCRE=n
CONFIG_LIGHTTPD=n
endif

ifeq ($(PROFILE),MR60)
IPV6RD_ENABLE_FLAG=y
INCLUDE_IPV6_FLAG=y
CONFIG_PPTP=y
CONFIG_RIP=y
CONFIG_SINGLE_PROCESS_PPPOE=y
MPOE_ENABLE_FLAG=y
CONFIG_STATIC_PPPOE=y
SAMBA_ENABLE_FLAG=n
CONFIG_NTFS_3G=n
#CONFIG_MTOOLS=y /* Foxconn, makred by MJ., for 3400v2 downsizing., 2011.02.21.  */
FTP_ACCESS_USB_FLAG=n
CONFIG_DLNA=n
CONFIG_L2TP=y
#CONFIG_IGMP_PROXY=y
CONFIG_ISERVER=n
CONFIG_TIMEMACHINE=n
CONFIG_KERNEL_2_6_36=n
CONFIG_OPENVPN=n
CONFIG_TCPDUMP=n
CONFIG_DOWNLOADER=n
#Foxconn add start, Snoopy.wu, support KWILT, 05/20/2015
CONFIG_KWILT=n
#foxconn Han added, 09/03/2015
CONFIG_LINK_AGG=n
CONFIG_PORTTRUNKING_SUPPORT=n
#CONFIG_BT_IGMP=y
CONFIG_ARNONAT=y
CONFIG_ORANGE_ISP=n
CONFIG_PCRE=n
CONFIG_LIGHTTPD=n
#foxconn Bernie added, 08/03/2019
ONLY_BUILD_SAMBA=y
ONLY_BUILD_DLNA=y
endif
ifeq ($(PROFILE),EAX20)
CONFIG_LLMNRD=y
CONFIG_NMBD=y
INCLUDE_IPV6_FLAG=n
IPV6RD_ENABLE_FLAG=n
CONFIG_ONE_SSID=y
endif
#Foxconn add end, Snoopy.wu, 05/20/2015

CONFIG_WGET=y
IPERF_ENABLE_FLAG=n

# 6rd support

#Foxconn added by Kathy, 04/03/2014 @ xAgent_cloud
CONFIG_CLOUD_XAGENT_CONF=y

CONFIG_NETATALK_3_1_8=n

BCA_HNDROUTER=y

CONFIG_CIRCLE_PARENTAL_CONTROL=n
