dynamic: install


all: install


install:
#	cp -f nvram_params_947622GW.save $(INSTALL_DIR)/etc/wlan/nvram_params
#	cp -f libnvram.so_947622GW.save $(INSTALL_DIR)/lib/libnvram.so
	cp -f nvram_params_RAX20.save $(INSTALL_DIR)/etc/wlan/nvram_params
	cp -f libnvram.so_RAX20.save $(INSTALL_DIR)/lib/libnvram.so	
